title: Nora Tseng
logo: /assets/img/headshot_2024-circle.png
description: Undergraduate Student at UW-Madison
  email            : ntseng@wisc.edu  
  linkedin         : 

# show_downloads: true
theme: jekyll-theme-minimal


# # Basic Site Settings
# locale                   : "en-US"
# title                    : "Your Name / Site Title"
# title_separator          : "-"
# name                     : &name "Your Name"
# description              : &description "personal description"
# url                      : https://academicpages.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
# repository               : "academicpages/academicpages.github.io"

# # Site Author - The following control what appear as part of the author content on the side bar.
# #               If a field is blank the icon and link will not appear, otherwise it will be shown.
# #               Additional customization can be done by editing /_includes/author-profile.html
# author:
#   # Biographic information
#   avatar           : "profile.png"
#   name             : "Your Sidebar Name"
#   pronouns         : # example: "she/her"  
#   bio              : "Short biography for the left-hand sidebar"
#   location         : "Earth"
#   employer         : "Red Brick University"
#   uri              : # URL
#   email            : "none@example.org" 

